/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\src\assets\greenleaf.glb --transform 
Files: .\src\assets\greenleaf.glb [1.28MB] > C:\Users\Daniel\Documents\web greenleaf\greenleaf\greenleaf-transformed.glb [249.12KB] (81%)
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/greenleaf-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={1000} near={0.01} fov={65.47} position={[-0.018, -0.019, 3.128]} />
      <mesh geometry={nodes.papel5001_Baked.geometry} material={materials['MergedBake_Baked.004']} position={[0.421, -0.525, -0.104]} rotation={[Math.PI, -0.059, -2.83]} />
    </group>
  )
}

useGLTF.preload('/greenleaf-transformed.glb')
